### ISSUE TITLE
fontan pangolin package links libpango_python against an undeclared libpython3.10 (breaks -dev builds on non-3.10 envs)

### ISSUE THREAD

**Issue by alejandrofontan** [VSLAM-LAB/VSLAM-LAB#143]
## Problem

The `pangolin` conda package in the `fontan` channel (`pangolin-2024.07.03-h3c9d71d_0`) ships `libpango_python.so.0.9.1` linked against `libpython3.10.so.1.0`, but its recipe declares no `python` dependency. Its `depends:` in `pixi.lock` is only glibc, epoxy, libpng, libxkbcommon, wayland.

Any environment that resolves a different Python and links against the full `Pangolin_LIBRARIES` list fails at link time. Observed today on `orbslam2-dev` (env resolved python 3.13):

```
x86_64-conda-linux-gnu-ld: warning: libpython3.10.so.1.0, needed by .pixi/envs/orbslam2-dev/lib/libpango_python.so.0.9.1, not found
x86_64-conda-linux-gnu-ld: .pixi/envs/orbslam2-dev/lib/libpango_python.so.0.9.1: undefined reference to `PyImport_ImportModule'
... (hundreds of Py* symbols)
collect2: error: ld returned 1 exit status
FAILED: Baselines/ORB-SLAM2-DEV/bin/vslamlab_orbslam2_mono
```

Before `install` gained a failure check (b48d073) this passed silently and surfaced later as a missing executable.

## Affected features

Eight features pull the package: `orbslam2`, `orbslam2-dev`, `orbslam3`, `orbslam3-dev`, `anyfeature`, `anyfeature-dev`, `dpvo`, `dpvo-dev`. Only the `-dev` ones link against it at install time; the conda-package ones ship prebuilt executables.

## Workaround in place

`python = "3.10.*"` pinned on `[feature.orbslam2-dev.dependencies]` (35e556c). The other `-dev` envs are unpinned and will hit the same error whenever their Python is not 3.10.

## Fix

Either of:
- Rebuild the package with `-DBUILD_PANGOLIN_PYTHON=OFF` (no baseline uses the Python bindings), or
- Declare the `python` run dependency (and `python_abi`) in the recipe so the solver keeps libpython3.10 present.

Until then: pin the remaining `-dev` envs, ideally by adding the existing `py10` feature to their environment definitions instead of an inline pin.
